### ISSUE TITLE
Multiple raspberry pi's incorrect registration

### ISSUE THREAD

**Issue by LsdGit** [ironsheep/lovelace-rpi-monitor-card#4]
Hi
Nice project.
I have 3 devices but only one appear in Integrations devices
seem like last last started device, override device configuration
all have exactly the same config.ini

![image](https://user-images.githubusercontent.com/3473511/89116913-e67d0e80-d4a1-11ea-941e-71f35ca3bf84.png)

**Comment by ironsheep** [comment]
Hi, glad you like it!

Yes, this is on me.  There was a point a couple of hours earlier today where I had committed this bug to the repo without knowing it.  I did get it fixed in a later release, now available. 

Your fix should be to simply refresh all three RPi's with the new code.  Before you do you may want to delete this device from Home Assistant.  

Just so you know I greatly suffer my own mistakes.  I had to reload 15 of my RPi's to get them all working again. The good news is that I found a couple of edge cases to fix making the latest release a bit stronger, sigh...

Again, I apologize for this. I'll try to catch these before I make a release (or publish to master) in the future.

**Comment by LsdGit** [comment]
Thank you, now work
