### ISSUE TITLE
Colour of free SD card space is reversed.

### ISSUE THREAD

**Issue by Darren-Hill** [ironsheep/lovelace-rpi-monitor-card#44]
### and have you...

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

### Version of RPi Monitor Card

Failing in 1.3.3, working in older version (not sure what I had)

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Browser and Operating system

Browser: Chrome
OS: Win10

### Description of problem

For devices with lots of free space (e.g. ~85% free) on the SD card, the Lovelace card shows a red icon, or a yellow one for slightly fuller devices. Devices with more full cards show blue (e.g. ~33% free).

This seems backwards to me, and it should be fuller devices that show yellow (warning) or red (alert) colouration?

### Errors in Browser Console

N/A

### Additional information

A cosmetic bug, but caused bit of a shock when I upgraded and saw it !

**Comment by ironsheep** [comment]
Thanks for reporting this. I'll be fixing the card and releasing it later today.  

I just repaired the Daemon which was reporting bad disk free-space.  This card had been correcting for the bad values and no longer needs to.  This is why the values appear inverted.   

FYI- Your title on this issue is better than mine but this is a duplicate of my (#41)

**Comment by Darren-Hill** [comment]
Excellent, thanks for the feedback, the fast work and the very useful script and card.

As this is a duplicate of #41, I'll close this issue off.
