### ISSUE TITLE
Some unknown new value appears on the card after update

### ISSUE THREAD

**Issue by BebeMischa** [ironsheep/lovelace-rpi-monitor-card#49]
### and have you...

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

### Version of RPi Monitor Card

1.4.1

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Browser and Operating system

Browser: Firefox latest
OS: Win 10 full up to date

### Description of problem

Some new value appears on the card after today's update

Don't know, what it means and if it's intentional

![afbeelding](https://user-images.githubusercontent.com/73079275/222183499-606aa626-4b49-4804-94c5-173c5a9ba2fa.png)

### Additional information

Thank you for looking in to it ;-)

**Comment by ironsheep** [comment]
Thanks for reporting this. I'll do two things:  (1) explain it better in the docs, and (2) fix one of the things you are seeing!

The `upd(1)` value means that RPi has at least 1 pending OS update.  This is a new feature of the system. You now can tell when there are many updates pending which is good to know as a large population of the updates are security fixes.

The 2nd thing is `upd(-1)` happens when the python3-apt package is not installed or not available for your Distro (such as Arch Linux).

I'll update the card to not show any (-1) values.   _Hmmm... I'd rather do this only for Arch Linux but I don't know how yet to detect that.  ;-)_

**Comment by ironsheep** [comment]
Changes committed, and appear in card/documents v1.4.2 and later.

**Comment by Vetti52** [comment]
As HA version later than March 2023 needs units of measurement, I have added 

sensor.rpi_hostname_rpi_monitor_hostname:
  friendly_name: Raspberry Pi4
  unit_of_measurement: "y"

into customize.yaml. So, at least, I can avoid a logfile entry at every 5 minutes.
But, maybe, there is a better solution.
